language: python
sudo: required
dist: trusty
python:
    - 2.7

env:
    - QGIS_REPO=http://qgis.org/debian-ltr

virtualenv:
    # Make apt installed Python packages work (i.e. PyQt) because Travis runs
    # tests in a virtualenv for Python 2.7.
    system_site_packages: true

addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - libnetcdf-dev
      - python-qt4  # is this needed?
      - xvfb  # emulating X-server

before_install:
    - sudo apt-get -qq -y update
    - cd .. && mv threedi-qgis-plugin ThreeDiToolbox && cd ThreeDiToolbox

install:
    # See: https://github.com/tomchadwin/qgis2web/blob/master/.travis.yml
    - sudo add-apt-repository ${QGIS_REPO}
    - sudo apt-get update
    - sudo apt-get install -y --force-yes qgis python-qgis
    # numpy and cython maybe needed for building netCDF4 (see netcdf4-python)
    # NOTE: coverage 4.0 is the last version that doesn't cause a segfault with test_project.py
    - pip install nose nose-exclude coverage==4.0 netCDF4==1.2.7 numpy==1.11.2 cython==0.19

script:
    - xvfb-run nosetests

notifications:
    email: false
