language: python
sudo: false
python:
    - 2.7
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libhdf5-serial-dev libnetcdf-dev
install:
    - pip install netCDF4 nose
script: nosetests
