language: python
sudo: required
python:
    - 2.7

env:
    - QGIS_REPO=http://qgis.org/debian-ltr

virtualenv:
    # Make apt installed Python packages work (i.e. PyQt) because Travis runs
    # tests in a virtualenv for Python 2.7.
    system_site_packages: true

addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - libnetcdf-dev
      - python-qt4

before_install:
    - python -c 'import PyQt4'

install:
    # See: https://github.com/tomchadwin/qgis2web/blob/master/.travis.yml
    - sudo add-apt-repository ${QGIS_REPO}
    - sudo apt-get update
    - sudo apt-get install -y --force-yes qgis python-qgis xvfb
    # numpy and cython maybe needed for building netCDF4 (see netcdf4-python)
    - pip install nose nose-exclude coverage netCDF4==1.2.7 numpy==1.7.0 cython==0.19

script:
    - cd .. && mv threedi-qgis-plugin ThreeDiToolbox && cd ThreeDiToolbox
    - nosetests ThreeDiToolbox.test.test_stats
    - nosetests ThreeDiToolbox.test.test_datasources
    - nosetests ThreeDiToolbox.test.test_models

notifications:
    email: false
