language: python
sudo: false
python:
    - 2.7

addons:
  apt:
    packages:
      - python-qgis
      - libhdf5-serial-dev
      - libnetcdf-dev

install:
    - pip install netCDF4 nose
script: cd .. && mv threedi-qgis-plugin ThreeDiToolbox && cd ThreeDiToolbox && nosetests
