language: python
sudo: false
python:
    - 2.7

addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - libnetcdf-dev
      - python-qt4

install:
    - pip install netCDF4 nose

script: cd .. && mv threedi-qgis-plugin ThreeDiToolbox && python -m unittest ThreeDiToolbox.test.test_stats

notifications:
    email: false
